routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::group(['middleware' => ['auth']], function () {

    Route::get('/', 'HomeController@index');

        Route::group(['middleware' => 'admin'], function() {
            Route::resources([
                'category' => 'CategoryController',
                'member_categories' => 'MemberCategoryController',
                
            ]);
        
    });

    Route::resources([

        'products' => 'ProductController',
        'promos' => 'PromoController',
        'transactions' => 'TransactionController',
        'members' => 'MemberController',
    ]);

    Route::get('/home', 'HomeController@index')->name('home');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $table='categories';
    protected $fillable=['name', 'desc'];
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    public function index(){
        $category = Category::all();
        return view('pages.categoryproduct', compact('category'));
    }
    public function destroy($id)
    {
        $category=Category::findOrFail($id);
        $category->delete();
        return back();
    
    }
    public function store()
    {

        request()->validate([
            'name' => 'required',
            'desc' => 'required',
        ]);
        $category = new Category();
        $category->id = request('id');
        $category->name = request('name');
        $category->desc = request('desc');
        $category->save();

        return redirect('category');
    }
    public function update(Category $category)
    {
        $category->update([
        'name' => request('name'),
        'desc' => request('desc'),
        ]);

        return redirect('category');
    }
    public function edit(Category $category)
    {
        return view('pages.category.editc', compact('category'));
        // return response()->json($category);
    }
}

resources/views/pages/category/editc.blade.php
@extends('app')

@section('content')

<div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>Input Category</h2>
                    <hr>
                    <ul class="header-dropdown m-r--5">
                        <li class="dropdown">
                            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <i class="material-icons">more_vert</i>
                            </a>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="javascript:void(0);">Action</a></li>
                                <li><a href="javascript:void(0);">Another action</a></li>
                                <li><a href="javascript:void(0);">Something else here</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="body">
                <div class="form-group">
                    <div class="row clearfix">
                        <div class="col-md-12">
                        <form action="{{ route('category.update', $category->id) }}" method="post" autocomplete="off" class="form-group">
                        @csrf
                        @method('put')
                                <div class="form-group">
                                  <label for="title">name</label>
                                  <div class="form-line">
                                  <input type="text" name="name" id="name" class="form-control" value="{{ $category->name }}">
                                  {!! $errors->first('name', '<span class="invalid-feedback">:message</span>') !!}
                                  </div>
                                  
                                </div>
                                <div class="form-group">
                                  <label for="desc">desc</label>
                                  <div class="form-line">
                                  <textarea type="text" name="desc" id="desc" class="form-control">{{ $category->desc }}</textarea>
                                  {!! $errors->first('desc', '<span class="invalid-feedback">:message</span>') !!}
                                  </div>
                                  </div>
                            <button type="submit" class="btn btn-primary">Save</button>
                        </form>
                        </div>
                    </div>
                </div>

                </div>
            </div>
        </div>
    </div>
    <!-- #END# Basic Table -->
    

@endsection