routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::group(['middleware' => ['auth']], function () {

    Route::get('/', 'HomeController@index');

        Route::group(['middleware' => 'admin'], function() {
            Route::resources([
                'category' => 'CategoryController',
                'member_categories' => 'MemberCategoryController',
                
            ]);
        
    });

    Route::resources([

        'products' => 'ProductController',
        'promos' => 'PromoController',
        'transactions' => 'TransactionController',
        'members' => 'MemberController',
    ]);

    Route::get('/home', 'HomeController@index')->name('home');
});

app/Product.php
<?php

namespace App;


use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $table='products';
    protected $guarded=['id'];

    public function product()
    {
        return $this->belongsTo(Category::class, 'product_category_id'); 
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use App\Category;
use DB;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    public function index(){
        $category = Category::all();
        $product = Product::all();
        return view('pages.product',compact('category', 'product'));
        // return response()->json($produt)
    }

    public function destroy($id)
    {
        $product = Product::findOrFail($id);
        $product->delete();
        return back();
    
    }

    public function store(Request $request)
    {

        // return response()->json($request);

        // $category = Category::all();
        $request->validate([
            'name' => 'required',
            'image'  =>  'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'product_category_id' => 'required',
            'desc' => 'required',
            'amount' => 'required',
        ]);
        // if ($request->has('active')) {
        //     $active = 1;
        //  } else {
        //      $active = 0;
        //  }

 
         $fileName = str_replace("=","",base64_encode($request->name.time())) . '.' . request()->image->getClientOriginalExtension();
 
         if(!$request->image->move(storage_path('app/public/promo'), $fileName)){
             return array('error' => 'Gagal upload foto');
         } else{

        $product = new Product();
        $product->name = $request->name;
        $product->image = "storage/promo/".$fileName;
        $product->product_category_id = $request->product_category_id;
        $product->desc = $request->desc;
        $product->amount = $request->amount;
        $product->save();

        }
        return redirect('products');
        // return response()->json($products);
    
    }
    
    public function update(Request $request, $id)
    {
        
        $productPict = Product::where("id","=",$id)->get()->first()->image;

        // return response()->json($productPict);

        if (!$request->image) {
            
            $request->validate([
                'name' => 'required',
                'product_category_id' => 'required',
                'desc' => 'required',
                'amount' => 'required'
            ]);
        } else {
            $request->validate([
                'name' => 'required',
                'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
                'product_category_id' => 'required',
                'desc' => 'required',
                'amount' => 'required'
            ]);

            $fileName = str_replace("=","",base64_encode($request->name.time())) . '.' . request()->image->getClientOriginalExtension();
        }
        
        if ($request->has('active')) {
            $active = 1;
        } else {
            $active = 0;
        }
        

        $product = Product::findOrFail($id);
        $product->name = $request->name;
        $product->product_category_id = $request->product_category_id;
        $product->desc = $request->desc;
        $product->amount = $request->amount;
        $product->image = $request->image;
        if($request->hasFile('image')){
            if (is_file($product->image)){
                try{
                    unlink($productPict);
                } catch(\Exception $e){

                }
            }
            $request->image->move(storage_path('app/public/produk'), $fileName);
            $product->image = "storage/produk/".$fileName;
        } else {
            $product->image = $productPict;
        }
        $product->save();

        return redirect('products');
    }
    
    public function edit(Product $product)
    {
        $category = Category::all();
        return view('pages.product.editp', compact('product', 'category'));
        
    }

}

resources/views/pages/product/editp.blade.php
@extends('app')

@section('content')

<div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>Input Product</h2>
                    <hr>
                    <ul class="header-dropdown m-r--5">
                        <li class="dropdown">
                            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <i class="material-icons">more_vert</i>
                            </a>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="javascript:void(0);">Action</a></li>
                                <li><a href="javascript:void(0);">Another action</a></li>
                                <li><a href="javascript:void(0);">Something else here</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="body">
                <div class="form-group">
                    <div class="row clearfix">
                        <div class="col-md-12">
                        <form action="{{ route('products.update', $product->id) }}" method="post" autocomplete="off" class="form-group" enctype="multipart/form-data">
                        @csrf
                        @method('put')
                                <div class="form-group">
                                  <label for="title">name</label>
                                  <div class="form-line">
                                  <input type="text" name="name" id="name" class="form-control" value="{{ $product->name }}">
                                  {!! $errors->first('name', '<span class="invalid-feedback">:message</span>') !!}
                                  </div>
                                  
                                </div>
                                <div class="form-group">
                                <div class="fallback">
                                  <label>Upload foto</label>
                                  <input type="file" name="image" id="image" class="form-control">
                                </div>

                                  </div>
                                  <div class="form-group">
                                    <label for="product_category_id">category</label>
                                    <div class="form-line">
                                        <select  class="form-control" name="product_category_id" id="product_category_id">
                                            <option disabled selected>Pilih Satu</option>
                                            @foreach($category as  $cat)
                                                <option {{ $product->product_category_id == $cat->id ? "selected" : "" }} value="{{ $cat->id }}">{{
                                                $cat->name }}</option>
                                            @endforeach
                                        </select> 
                                    </div>
                                  </div>
                                  <br><div class="form-group">
                                  <label for="desc">desc</label>
                                  <div class="form-line">
                                  <textarea type="text" name="desc" id="desc" class="form-control">{{ $product->desc }}</textarea>
                                  {!! $errors->first('desc', '<span class="invalid-feedback">:message</span>') !!}
                                  </div>

                                  </div>
                                <div class="form-group">
                                  <label for="image">amount</label>
                                  <div class="form-line">
                                  <input type="text" name="amount" id="amount" class="form-control" value="{{ $product->amount }}">
                                  {!! $errors->first('amount', '<span class="invalid-feedback">:message</span>') !!}
                                  </div>
                                  </div>
                            <button type="submit" class="btn btn-primary">Save</button>
                        </form>
                        </div>
                    </div>
                </div>

                </div>
            </div>
        </div>
    </div>
    <!-- #END# Basic Table -->
    

@endsection