routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::group(['middleware' => ['auth']], function () {

    Route::get('/', 'HomeController@index');

        Route::group(['middleware' => 'admin'], function() {
            Route::resources([
                'category' => 'CategoryController',
                'member_categories' => 'MemberCategoryController',
                
            ]);
        
    });

    Route::resources([

        'products' => 'ProductController',
        'promos' => 'PromoController',
        'transactions' => 'TransactionController',
        'members' => 'MemberController',
    ]);

    Route::get('/home', 'HomeController@index')->name('home');
});

resources/views/pages/categoryproduct.blade.php
@extends('app')

@section('content')

<div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>Input Category</h2>
                    <hr>
                    <ul class="header-dropdown m-r--5">
                        <li class="dropdown">
                            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <i class="material-icons">more_vert</i>
                            </a>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="javascript:void(0);">Action</a></li>
                                <li><a href="javascript:void(0);">Another action</a></li>
                                <li><a href="javascript:void(0);">Something else here</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="body">
                <div class="form-group">
                    <div class="row clearfix">
                        <div class="col-md-12">
                        <form action="" method="post" autocomplete="off" class="form-group">
                        @csrf
                                <div class="form-group">
                                  <label for="name">name</label>
                                  <div class="form-line">
                                  <input type="text" name="name" id="name" class="form-control">
                                  {!! $errors->first('name', '<span class="invalid-feedback">:message</span>') !!}
                                  </div>
                                  
                                </div>
                                <div class="form-group">
                                  <label for="desc">desc</label>
                                  <div class="form-line">
                                  <textarea type="text" name="desc" id="desc" class="form-control"></textarea>
                                  {!! $errors->first('desc', '<span class="invalid-feedback">:message</span>') !!}
                                  </div>
                                  </div>
                            <button type="submit" class="btn btn-primary">Save</button>
                        </form>
                        </div>
                    </div>
                </div>
                <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2> All Category </h2>
                            <ul class="header-dropdown m-r--5">
                                <li class="dropdown">
                                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                        <i class="material-icons">more_vert</i>
                                    </a>
                                    <ul class="dropdown-menu pull-right">
                                        <li><a href="javascript:void(0);">Action</a></li>
                                        <li><a href="javascript:void(0);">Another action</a></li>
                                        <li><a href="javascript:void(0);">Something else here</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        <div class="body table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>no</th>
                                        <th>name</th>
                                        <th>desc</th> 
                                    </tr>
                                    
                                </thead>
                                <tbody>
                                @foreach ($category as $n => $cat)
                                <tr>
                                    <td>{{ $n+1 }}</td>
                                    <td>{{ $cat->name }}</td>
                                    <td>{{ $cat->desc }}</td>
                                    
                                    <td><a href="{{ route('category.edit', $cat->id) }}"><button type="submit" class="btn btn-success">Update</button></a></td>
                                    
                                    </form>
                                    <form action="{{ route('category.destroy', $cat->id) }}" method="post">
                                    @csrf
                                    @method('delete')
                                    <td><button type="submit" class="btn btn-danger">Delete</button></td>
                                    </form>
                                </tr>
                                @endforeach
                                </tbody>
                            </table> 
                                    <a href="category"><button class="btn btn-primary" type="submit">Create</button></a> 
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
    <!-- #END# Basic Table -->
    

@endsection

resources/views/pages/member.blade.php
@extends('app')

@section('content')

<div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>Input Member</h2>
                    <hr>
                    <ul class="header-dropdown m-r--5">
                        <li class="dropdown">
                            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <i class="material-icons">more_vert</i>
                            </a>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="javascript:void(0);">Action</a></li>
                                <li><a href="javascript:void(0);">Another action</a></li>
                                <li><a href="javascript:void(0);">Something else here</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="body">
                <div class="form-group">
                    <div class="row clearfix">
                        <div class="col-md-12">
                        <form action="" method="post" autocomplete="off" class="form-group">
                        @csrf
                        <div class="form-group">
                                <div class="form-line">
                                    <select  class="form-control show-tick" name="member_category_id" id="member_category_id">
                                <option disabled selected>Categories</option>
                                @foreach ($membercategory as $memcat)
                                    <option value="{{ $memcat->id }}"> {{ $memcat->name }} </option>    
                                @endforeach
                            </select>
                        </div>
                        </div>
                        <br><div class="form-group">
                                  <label for="Full name">Full name</label>
                                  <div class="form-line">
                                  <input type="text" name="fullname" id="fullname" class="form-control">
                                  {!! $errors->first('Full name', '<span class="invalid-feedback">:message</span>') !!}
                                  </div>
                                </div>
                        <div class="input-group date" id="bs_datepicker_component_container">
                            <label for="dob">Day Of Birth</label>
                                <div class="form-line">
                                    <input type="date" name="dob" id="dob" class="form-control" placeholder="Please choose a date...">
                                </div>
                            </div>
                            <div class="form-group">
                                  <label for="address">Address</label>
                                  <div class="form-line">
                                  <input type="text" name="address" id="address" class="form-control">
                                  {!! $errors->first('address', '<span class="invalid-feedback">:message</span>') !!}
                                  </div>
                                </div>
                        <div class="form-group">
                        <label for="gender">Gender</label>
                            <div class="demo-radio-button"><br>
                                <input name="gender" type="radio" id="laki-laki" value="laki-laki" class="with-gap" checked />
                                <label for="laki-laki">Laki-laki</label>
                                <input name="gender" type="radio" id="perempuan" value="perempuan" class="with-gap" />
                                <label for="perempuan">Perempuan</label>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2> All Member </h2>
                            <ul class="header-dropdown m-r--5">
                                <li class="dropdown">
                                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                        <i class="material-icons">more_vert</i>
                                    </a>
                                    <ul class="dropdown-menu pull-right">
                                        <li><a href="javascript:void(0);">Action</a></li>
                                        <li><a href="javascript:void(0);">Another action</a></li>
                                        <li><a href="javascript:void(0);">Something else here</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        <div class="body table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>no</th>
                                        <th>member_category_id</th>
                                        <th>fullname</th>
                                        <th>dob</th>
                                        <th>address</th>
                                        <th>gender</th>
                                        <th>barcode</th>
                                        
                                    </tr>
                                    
                                </thead>
                                <tbody>
                                @foreach ($members as $n => $mem)
                                <tr>
                                    <td>{{ $n+1 }}</td>
                                    <td>{{ $mem->member_category_id }}</td>
                                    <td>{{ $mem->fullname }}</td>
                                    <td>{{ $mem->dob }}</td>
                                    <td>{{ $mem->address }}</td>
                                    <td>{{ $mem->gender }}</td>
                                    <td>{{ $mem->barcode }}</td>
                                    <td><a href="{{ route('members.edit', $mem->id) }}"><button type="button" class="btn btn-success">Update</button></a></td>
                                    </form>
                                    <form action="{{ route('members.destroy', $mem->id) }}" method="post">
                                    @csrf
                                    @method('delete')
                                    <td><button type="submit" class="btn btn-danger">Delete</button></td>
                                    </form>
                                </tr>
                                @endforeach
                                </tbody>
                            </table>
                                <a href="members"><button type="submit" class="btn btn-primary">Create</button></a>   
                        </div>
                    </div>
                    </div>
                </div>

                </div>
            </div>
            
        </div>
    </div>
    </div>
    <!-- #END# Basic Table -->
    

@endsection

resources/views/pages/member_categories.blade.php
@extends('app')

@section('content')

<div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>Input Member Category</h2>
                    <hr>
                    <ul class="header-dropdown m-r--5">
                        <li class="dropdown">
                            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <i class="material-icons">more_vert</i>
                            </a>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="javascript:void(0);">Action</a></li>
                                <li><a href="javascript:void(0);">Another action</a></li>
                                <li><a href="javascript:void(0);">Something else here</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="body">
                <div class="form-group">
                    <div class="row clearfix">
                        <div class="col-md-12">
                        <form action="" method="post" autocomplete="off" class="form-group">
                        @csrf
                                <div class="form-group">
                                  <label for="name">name</label>
                                  <div class="form-line">
                                  <input type="text" name="name" id="name" class="form-control">
                                  {!! $errors->first('title', '<span class="invalid-feedback">:message</span>') !!}
                                  </div>
                                </div>
                            <button type="submit" class="btn btn-primary">Save</button>
                        </form>
                        </div>
                        <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2> All Member </h2>
                            <ul class="header-dropdown m-r--5">
                                <li class="dropdown">
                                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                        <i class="material-icons">more_vert</i>
                                    </a>
                                    <ul class="dropdown-menu pull-right">
                                        <li><a href="javascript:void(0);">Action</a></li>
                                        <li><a href="javascript:void(0);">Another action</a></li>
                                        <li><a href="javascript:void(0);">Something else here</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        <div class="body table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>no</th>
                                        <th>name</th>
 
                                    </tr>
                                    
                                </thead>
                                <tbody>
                                @foreach ($membercategory as $n => $memcat)
                                <tr>
                                    <td>{{ $n+1 }}</td>
                                    <td>{{ $memcat->name }}</td>
                                    
                                    <td><a href="{{ route('member_categories.edit', $memcat->id) }}"><button type="submit" class="btn btn-success">Update</button></a></td>
                                    
                                    </form>
                                    <form action="{{ route('member_categories.destroy', $memcat->id) }}" method="post">
                                    @csrf
                                    @method('delete')
                                    <td><button type="submit" class="btn btn-danger">Delete</button></td>
                                    </form>
                                </tr>
                                @endforeach
                                </tbody>
                            </table> 
                                    <a href="membercategory"><button class="btn btn-primary" type="submit">Create</button></a> 
                        </div>
                    </div>
                </div>
                    </div>
                </div>
        </div>
    </div>
    <!-- #END# Basic Table -->

@endsection

resources/views/pages/product.blade.php
@extends('app')

@section('content')

<div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>Input Product</h2>
                    <hr>
                    <ul class="header-dropdown m-r--5">
                        <li class="dropdown">
                            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <i class="material-icons">more_vert</i>
                            </a>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="javascript:void(0);">Action</a></li>
                                <li><a href="javascript:void(0);">Another action</a></li>
                                <li><a href="javascript:void(0);">Something else here</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="body">
                <div class="form-group">
                    <div class="row clearfix">
                        <div class="col-md-12">
                        <form action="" method="post" autocomplete="off" class="form-group" enctype="multipart/form-data">
                        @csrf
                                <div class="form-group">
                                  <label for="name">name</label>
                                  <div class="form-line">
                                  <input type="text" name="name" id="name" class="form-control">
                                  {!! $errors->first('name', '<span class="invalid-feedback">:message</span>') !!}
                                  </div>
                                  
                                </div>
                                <div class="form-group">
                                <div class="fallback">
                                  <label>Upload foto</label>
                                  <input type="file" name="image" id="image" class="form-control">
                                
                                  </div>

                                </div>
                                <div class="form-group">
                                    <label for="product_category_id">category</label>
                                    <div class="form-line">
                                        <select  class="form-control" name="product_category_id" id="product_category_id">
                                            <option disabled selected>Pilih Satu</option>
                                            @foreach($category as  $cat)
                                                <option value="{{ $cat->id }}"> {{ $cat->name }}</option>
                                            @endforeach
                                        </select> 
                                    </div>
                                  </div>
                                  <br><div class="form-group">
                                  <label for="desc">desc</label>
                                  <div class="form-line">
                                  <textarea type="text" name="desc" id="desc" class="form-control"></textarea>
                                  {!! $errors->first('desc', '<span class="invalid-feedback">:message</span>') !!}
                                  </div>

                                </div>
                                <div class="form-group">
                                  <label for="ampount">amount</label>
                                  <div class="form-line">
                                  <input type="text" name="amount" id="amount" class="form-control">
                                  {!! $errors->first('amount', '<span class="invalid-feedback">:message</span>') !!}
                                  </div>
                                  </div>
                            <button type="submit" class="btn btn-primary">Save</button>
                        </form>
                        </div>
                    </div>
                </div>
                <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2> All Product </h2>
                            <ul class="header-dropdown m-r--5">
                                <li class="dropdown">
                                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                        <i class="material-icons">more_vert</i>
                                    </a>
                                    <ul class="dropdown-menu pull-right">
                                        <li><a href="javascript:void(0);">Action</a></li>
                                        <li><a href="javascript:void(0);">Another action</a></li>
                                        <li><a href="javascript:void(0);">Something else here</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        <div class="body table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>no</th>
                                        <th>name</th>
                                        <th>image</th>
                                        <th>product_category_id</th>
                                        <th>desc</th>
                                        <th>amount</th>
                                    </tr>
                                    
                                </thead>
                                <tbody>
                                @foreach ($product as $n => $pro)
                                <tr>
                                    <td>{{ $n+1 }}</td>
                                    <td>{{ $pro->name }}</td>
                                    <td><img src="{{ $pro->image }}" height="80px" alt="gambar"></td>
                                    <td>{{ $pro->product['name'] }}</td>
                                    <td>{{ $pro->desc }}</td>
                                    <td>{{ $pro->amount }}</td>
                                    <td><a href="{{ route('products.edit', $pro->id) }}"><button type="button" class="btn btn-success">Update</button></a></td>
                                   
                                    <form action="{{ route('products.destroy', $pro->id) }}" method="post">
                                    @csrf
                                    @method('delete') 
                                    <td><button type="submit" class="btn btn-danger">Delete</button></td>
                                    </form>
                                </tr>
                                @endforeach
                                </tbody>
                            </table>
                                <a href="products"><button type="submit" class="btn btn-primary">Create</button></a>   
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- #END# Basic Table -->
    

@endsection